import pycep_correios
from geopy.geocoders import Nominatim
import csv

csv_headers = ['latitude','longitude']
with open('lat_long_locais_petfriendly.csv', 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(csv_headers)

endereco = [
    "Av. Manoel Ribas, 5480",
    "R. Padre Chagas, 306",
    "Dinarte Ribeiro, 148",
    "Av. Túlio de Rose, 80",
    "Av Borges de Medeiros, 1518",
    "R. Bela Cintra, 1783",
    "Rua Wilma Dinnebier, 180",
    "Av. Borges de Medeiros, 2784",
    "Servidão da Magia, 75",
    "Rua Bocaiúva, 2304",
    "SC 438, km 130",
    "Estrada do Faxinal, RS-427",
    "R. Garibaldi, 254",
    "Rua Dr. Vale, 579",
    "Avenida Borges de Medeiros, 3166",
    "Estrada Vicinal, 555",
    "Avenida Brasil, 1196",
    "Rua Santa Cruz, 665",
    "Estrada Linha Ávila, 2520",
    "Rua Baltazar Carrasco, 187",
    "R. Itabaiana, 727",
    "R. Cândido Bueno, 746",
    "R. Cel. Dulcídio, 558",
    "R. Solimões, 681",
    "R. Mateus Leme, 4715",
    "Alameda Dom Pedro II, 255",
    "R. Horácio Cardoso, 291",
    "Largo Benito Urbani, 77",
    "Avenida 15 de Novembro, 1057",
    "R. Me. Verônica, 61",
    "Largo Benito Urbani",
    "R. Hilário Ribeiro, 281",
    "R. Buenos Aires, 50",
    "R. São Pedro, 401",
    "Rua 24 de Maio, 144",
    "Rua João Gava, 920",
    "Av. Sete de Setembro",
    "Rua Bruno Filgueira, 666",
    "Av. Cândido Hartmann",
    "R. Pascal, 249",
    "Av. Angélica, 2285",
    "R. Augusta, 2840",
    "R. Dr. Mário Ferraz, 32",
    "R. Pelotas 299",
    "Av. Rebouças, 3415",
    "R. Voltaire, 170",
    "Alameda Franca, 1552",
    "R. Joaquim Távora, 1415",
    "R. Cisplatina, 31",
    "R. Roberto Carbonari, 135",
    "Rua Antônio Joaquim de Oliveira, 3363",
    "Av. Antônio Joaquim de Oliveira, 2600",
    "Av Monte Verde, 790",
    "Av. Monte Verde, 945",
    "R Rolinha, 40",
    "Av. Pedroso de Morais, 148",
    "Alameda dos Jurupis, 1920",
    "R. Clodomiro Amazonas, 473",
    "Rua Guaimbé, 439",
    "Avenida Paulo Ribas, No 165",
    "Estrada Santa Inês, 3000",
    "Avenida Engenheiro Caetano Álvares, 5444",
    "Av. Higienópolis",
    "Av. Horácio Lafer, 533",
    "Av. Horácio Lafer, 541",
    "Av. Império do Sol Nascente, 643",
    "Rua Alexandre Dumas 1518",
    "Mourato Coelho, 1223",
    ". Jerônimo da Veiga, 198",
    "Alameda Lorena, 1271",
    "R. Conselheiro Brotero, 1120",
    "Rua Édison, 1418",
    "R. Alagoas, 642",
    "R. Bueno Brandão, 80",
    "Rua Augusto Tolle, 279",
    "Rua Luís Góis, 1625",
    "R. Ismael Neri, 485",
    "R. Estado de Israel, 227",
    "Av. Otto Baumgart, 500",
    "R. Manuel Guedes, 233",
    "R. Pará, 252",
    "Av. Morumbi, 5594",
    "R. Agostinho Gomes, 2013",
    "Av. Antônio Joaquim de Oliveira, 647",
    "R. Casa do Ator, 608",
    "Av. Monte Verde, 858",
    "Alameda Santos, 1437",
    "R. Pedro Benetti, 22",
    "R. Irmã Gabriela, 51",
    "Av. Juriti, 629",
    "R. Virgo, 203",
    "Av. Pedro de Paula Moraes, 341",
    "Av. Miguel Estefno, 3001",
    "Estr. Guaxinduva, 1145",
    "Rodovia Octavio de Oliveira Santos, 6",
    "Estrada do Funil, Km 16",
    "R. São Pedro de Alcântara, 269",
    "Av. das Nações Unidas, 13301",
    "R. Arturo Toscanini, 61",
    "R. do Passeio, 83",
    "R. Alves Guimarães, 153",
    "R. Graúna, 87",
    "R. Garibaldi, 254",
    "R. Afonso Braz, 657",
    "R. Itapacurai, 267",
    "R. Jorge da Silva Prado, 39",
    "Av. Paquetá, 423",
    "Estrada do Cha Km 4",
    "Rua Coropé, 57",
    "R. Gustavo Sampaio, 320",
    "Rua Santa Terezinha, 29",
    "Av. Professora Maria do Carmo Guimarães Pellegrini, 100",
    "Rua Tinhorão, 130",
    "Alameda Itu, 225",
    "R. Vupabussu, 305",
    "Rua Cardeal Arcoverde, 2773",
    "R. Dr. Mário Totta, 963",
    "Av. Guilherme Campos, 500",
    "R. Vupabussu, 271",
    "R. Dória Vasconcelos, 144",
    "R. Inocêncio de Melo Franco, 231",
    "R. Bueno Brandão, 66",
    "Rua Miguel Pera, 210",
    "Av. Antônio Joaquim de Oliveira, 265",
    "R. Dinarte Ribeiro, 56",
    "R. dos Pinheiros, 434",
    "R. Martim Francisco, 244",
    "R. Cap. Pacheco e Chaves, 313",
    "R. Cristiano Viana, 480",
    "R. Joaquim Távora, 1517",
    "Av. Conselheiro Rodrigues Alves, 456",
    "Rua Tupi, 228",
    "R. Joaquim Antunes, 367",
    "Rua Brás Cardoso, 342",
    "Av. Andrômeda, 227",
    "R. Oscar Freire, 163",
    "R. Oscar Freire, 45",
    "Av. Nazaré, 1732",
    "Av. Pereira Barreto, 42",
    "Estrada da Fonte, 1352",
    "R. Comendador Miguel Calfat, 289",
    "R. Sampaio Vidal, 1072",
    "Av. Atlântica, 4240",
    "R. Alm. Alexandrino, 660",
    "R. Ronald de Carvalho, 275",
    "Av. Lúcio Costa, s/ n",
    "Rua Dias Ferreira, 12",
    "R. Visc. de Carandaí, 5",
    "R. Oscar Freire, 155",
    "Av. Giovanni Gronchi, 5930",
    "R. Bromélias, 206",
    "Alameda dos Arapanés, 1307",
    "Av. Praias do Litoral, 99",
    "Av. Júlio de Mesquita, 705",
    "R. Prof. Filadelfo Azevedo, 717",
    "R. Dep. Laércio Corte, 1501",
    "Av. Campeche, 1836",
    "R. Sebastião Romão César, 508",
    "R. Cora coralina, 350",
    "Av. Atlântica, 1020",
    "Estrada geral santa barbara, s/n",
    "MG 451- Km 23",
    "Av. das Montanhas, 120",
    "Alameda Lorena, 672",
    "R. Cap. Pacheco e Chaves, 313",
    "Av. Higienópolis, 698",
    "R. Diogo Jácome, 606",
    "R. Gironda, 188",
    "Av. Ayrton Senna da Silva, 32",
    "R. dos Pinheiros, 476",
    "Praça Giordano Bruno - Vila Mariana",
    "R. Francisco Duarte, 33",
    "Av. Mal. Deodoro da Fonseca, 367",
    "Av. Pedro de Paula Moraes, s/n",
    "Av. Brasil, 1770",
    "Av. Magalhães de Castro, 286",
    "Rua Benjamim Egas, 297",
    "R. Domingos Leme, 284",
    "Rua da Praia, 501",
    "Rodovia Octavio de Oliveira Santos, s/n",
    "Estrada de Jarinu, km 12",
    "Av. Dr. Luis Arrobas Martins, 1880",
    "Alameda Prof. Lucas Nogueira Garcez, 7568",
    "R. Itabaiana, 727",
    "R. Pamplona, 869",
    "Av. Pequeno Príncipe, 2676",
    "Av. Giovanni Gronchi, 5930",
    "R. Jacques Félix, 696",
    "DF-451",
    "R. Gen. Osório, 1059",
    "Estrada, Caminho dos Açores, 1740",
    "Praça Ângelo Falgetano - Campo Belo",
    "Estr. Terra Boa, S/N",
    "Rua Djalma Forjaz, 93",
    "R. Três, 308",
    "Praça Oswaldo Cruz, 26",
    "Praça Libanesa, 100",
    "Av. Raimundo Pereira de Magalhães, 1465",
    "Rua Tinhorão, 130",
    "Av. Pedroso de Morais, 267",
    "Rua Pirapora, 218",
    "Av. Giovanni Gronchi, 5930",
    "R. Itapura, 1128",
    "Av. Macedo Soares, 262",
    "Rua Djalma Forjaz, 139",
    "Av. Macedo Soares, 203",
    "Rua Djalma Forjaz, 89",
    "Av. Macedo Soares, 457",
    "Av. Borges de Medeiros, 1595",
    "Estrada do Machadinho KM 4",
    "Av. Edvaldo Pereira Paiva",
    "Rua Inácio Vasconcelos, 49",
    "Av. Cristóvão Colombo, 3192",
    "Av. Borges de Medeiros, 2760",
    "R. Dinarte Ribeiro, 155",
    "Av. Borges de Medeiros, 2784",
    "R. Padre Chagas, 75",
    "Alameda Alípio César, 22",
    "Rua Boca da Serra, 445",
    "Av. dos Estados, 1909",
    "Largo Benito Urbani, 77/3",
    "Av. Edvaldo Pereira Paiva, 71",
    "Rua Felisberto Soares, 258",
    "R. Carlos Weber, 750",
    "R. Dinarte Ribeiro, 155",
    "R. Jacques Félix, 626A",
    "R. da República, 358",
    "R. Padre Chagas, 288",
    "R. Alagoas, 361",
    "Av. Venâncio Aires, 639",
    "Av. Mauá, 1050",
    "Rodovia Dom Pedro I, Km 131",
    "R. Pedroso Alvarenga, 843",
    "R. Padre Chagas, 306",
    "R. Dr. Florêncio Ygartua, 374",
    "R. Mateus Grou, 355",
    "Rua Harmonia, 880",
    "R. Caconde, 118",
    "R. Croata, 703",
    "R. Júlio Diniz, 39",
    "R. Nova York, 570",
    "R. Simão Álvares, 31",
    "R. Caconde, 132",
    "Av. das Nações Unidas, 12901",
    "R. Dr. Paulo Dias, 142",
    "R. Pedro Cristi, 89",
    "R. Havaí, 88",
    "R. Gen. Osório, 420",
    "Av. Prof. Alfonso Bovero, 637",
    "Alameda Franca, 1349",
    "R. Pamplona, 1704",
    "Alameda Lorena, 884",
    "Av. Força Expedicionária Brasileira, 234",
    "R. das Zamboeiras, 110",
    "R. Traipu, 156",
    "R. Antônio Carlos, 404",
    "R. Conselheiro Brotero, 744",
    "Av. Prof. Fonseca Rodrigues, 2001",
    "R. Caminho do Rei, 1001",
    "R. Albatroz, 553",
    "R. Fradique Coutinho, 1340",
    "R. Girassol, 273",
    "R. Palestra Itália, 500",
    "R. Sena Madureira, 1355",
    "Estr. Laramara, 3500",
    "Rua Joinville, 515",
    "R. Dr. Mário Ferraz, 589",
    "R. Maria Figueiredo, 181",
    "Alameda Olga, 300",
    "Rua Belo Horizonte, 119",
    "R. dos Pinheiros, 513",
    "Av. Atlântica",
    "Estrada da Barra da Tijuca, 420",
    "Av. Pavão, 840",
    "R. Comendador Miguel Calfat, 70",
    "Alameda Lorena, 1889",
    "R. Quintana, 719",
    "R. Jerônimo da Veiga, 30",
    "Av. Giovanni Gronchi, 5930",
    "Av. Giovanni Gronchi, 5930",
    "R. Canuto Abreu, s/n",
    "Av. Henrique Chamma, 420",
    "Av. Nazaré, s/n",
    "Av. Angélica, 1500",
    "Rua Muniz de Sousa, 1.119",
    "Av. Governador Mário Covas Júnior, 14500",
    "Av. das Nações Unidas, 12559",
    "Av. Marquês de São Vicente, 1619",
    "R. Pedroso Alvarenga, 610",
    "R. José Maria Lisboa, 1000",
    "R. Sansão Alves dos Santos",
    "R. João Cachoeira, 278",
    "R. Bem-te-vi, 15",
    "Av. da Fazenda, 10",
    "R. Pau Brasil, 801",
    "R. Cap. Salomão, 14 D",
    "Av. Ataulfo de Paiva, 1240",
    "Rua Dias Ferreira, 147",
    "R. Canuto do Val, 177",
    "Praça São Marcos, 825",
    "R. Barata Ribeiro, 507",
    "R. Maria Quitéria, 70",
    "Rua Pacheco Leão, 320",
    "Estrada da Barra da Tijuca, 1636",
    "R. Piracuama, 155",
    "R. Mateus Grou, 488",
    "R. Augusta, 2542",
    "Rua Cristovao de Burgos, 74",
    "R. Mateus Grou, 80",
    "R. Oscar Freire, 42",
    "R. Manuel Guedes, 281",
    "Praça Pereira Coutinho, 182",
    "Av. Dr. Cardoso de Melo, 586",
    "R. Joaquim Távora, 1356",
    "R. Dr. Renato Paes de Barros, 415",
    "Rua Pais de Araújo, 129",
    "R. dos Pinheiros, 320",
    "R. Mateus Grou, 50",
    "R. Delfina, 196",
    "R. Artur de Azevedo, 986",
    "R. Bela Cintra, 1599",
    "Av. Magalhães de Castro, 12000",
    "Av. Higienópolis, 698",
    "Alameda Lorena, 1914",
    "Alameda Lorena, 1271",
    "R. Pedroso Alvarenga, 672",
    ". Maria Quitéria, 68",
    "Av. Atlântica, 1702",
    "Av. do Pepê",
    "RUA VOLUNTÁRIOS DA PÁTRIA, 31",
    "R. Paulo Barreto, 65",
    ". Voluntários da Pátria, 446",
    "R. Rui Barbosa, 192",
    "R. Leopoldo Couto Magalhães Júnior, 1219",
    "R. Cerro Corá, 1841",
    "R. Diana, 637",
    "R. Caraíbas, 871",
    "Alameda Lorena, 1295",
    "Prof. Filadelfo Azevedo, 717",
    "Rua Peixoto Gomide, 190",
    "Rua Coropé, 51",
    "Alameda Tietê, 110",
    "Rua Dias Ferreira, 233",
    "Av. Olegário Maciel, 175",
    "Estr. do Rio Morto, 541",
    "Rua Garcia d'Avila, 134",
    "Av. Lúcio Costa, 5750",
    "Rua Dias Ferreira, 113",
    "Av. Lúcio Costa, 5210",
    "Av. Atlântica, 3668",
    "R. Paulino Fernandes, 39",
    "Av. Embaixador Abelardo Bueno, 1430",
    "Av. Atlântica, 1702",
    "Av. das Américas, 8585",
    "R. Jacques Félix, 253",
    "R. Valois de Castro, 51",
    "R. Paulo Maldi, 124",
    "Rua Monte Serrat, 1439",
    "Alameda Lorena, 1285",
    "R. José Maria Lisboa, 891",
    "R. Marivaldo Fernandes, 144",
    "Av. Paulista, 2355",
    "R. Sebastião Romão César, 184",
    "Av. Ernesto Diederichsen, 2962",
    "Av. Antônio Joaquim de Moura Andrade, 737",
    "R. Minas Gerais, 352",
    "Av. Brigadeiro Luís Antônio, 4700",
    "R. Jacurici, 27",
    "Av. Mãe Bernarda, 2176",
    "Alameda dos Arapanés, 1307",
    "Av. Magalhães de Castro, 12000",
    "Rua Joinville, 515",
    "R. Olimpíadas, 205",
    "Av. Magalhães de Castro, 12000",
    "R. José Félix de Oliveira, 555",
    "Av. Pedro Álvares Cabral",
    "R. Oscar Freire, 187",
    "R. Lourenço de Almeida, 470",
    "Av. Monte Verde, 743",
    "R. Caravelas, 339",
    "R. João Cachoeira, 1463",
    "Rua Prudente de Moraes, 110",
    "Av. Magalhães de Castro, 12000"
]

for e in endereco:
    locator = Nominatim(user_agent="myGeocoder")
    location = locator.geocode(e)
    # print(e,"    ", location.latitude,"    ", location.longitude)

    with open('lat_long_locais_petfriendly.csv', 'a', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow([location.latitude, location.longitude])