package petfinder.petfinderapi.enums;

public enum EnumStatusDemanda {
    ABERTO,
    CONCLUIDO,
    CANCELADO,
    DOCUMENTO_VALIDO,
    PGTO_REALIZADO_USER,
    PAGAMENTO_REALIZADO_USER,
    PGTO_REALIZADO_INST,
    PAGAMENTO_REALIZADO_INST,
    RESGATE_INVALIDO,
    RESGATE_VALIDO;

}
